### ISSUE TITLE
Can't compile in macOS 10.15

### ISSUE THREAD

**Issue by ludufre** [fortenbt/Ghidra-SMB3INES-Loader#3]
Hi, I can't compile on macOS 10.15.4

```bash
ludufre@MacBook-Pro-de-Luan Ghidra-SMB3INES-Loader-master % echo $JAVA_HOME 
/Library/Java/JavaVirtualMachines/jdk-11.0.7.jdk/Contents/Home
ludufre@MacBook-Pro-de-Luan Ghidra-SMB3INES-Loader-master % echo $GHIDRA_INSTALL_DIR
/Users/ludufre/Downloads/ghidra_9.1.2_PUBLIC
ludufre@MacBook-Pro-de-Luan Ghidra-SMB3INES-Loader-master % ./gradlew

> Task :compileJava FAILED
/Users/ludufre/Downloads/Ghidra-SMB3INES-Loader-master/src/main/java/smb3inesloader/SMB3INESLoader.java:17: error: cannot find symbol
import ghidra.app.util.importer.MemoryConflictHandler;
                               ^
  symbol:   class MemoryConflictHandler
  location: package ghidra.app.util.importer
/Users/ludufre/Downloads/Ghidra-SMB3INES-Loader-master/src/main/java/smb3inesloader/SMB3INESLoader.java:112: error: cannot find symbol
            MemoryConflictHandler handler, TaskMonitor monitor, MessageLog log) throws CancelledException, IOException {
            ^
  symbol:   class MemoryConflictHandler
  location: class SMB3INESLoader
/Users/ludufre/Downloads/Ghidra-SMB3INES-Loader-master/src/main/java/smb3inesloader/SMB3INESLoader.java:36: error: SMB3INESLoader is not abstract and does not override abstract method load(ByteProvider,LoadSpec,List<Option>,Program,TaskMonitor,MessageLog) in AbstractLibrarySupportLoader
public class SMB3INESLoader extends AbstractLibrarySupportLoader {
       ^
/Users/ludufre/Downloads/Ghidra-SMB3INES-Loader-master/src/main/java/smb3inesloader/SMB3INESLoader.java:110: error: method does not override or implement a method from a supertype
    @Override
    ^
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
ludufre@MacBook-Pro-de-Luan Ghidra-SMB3INES-Loader-master % 
```

**Comment by ardavank** [comment]
Use Ghidra version 9.0 instead of the latest version
